spring.application.name=minhajvault


spring.config.import=vault://

spring.cloud.vault.uri=http://localhost:8200
spring.cloud.vault.authentication=APPROLE
spring.cloud.vault.app-role.role-id=6b8d52da-dd6e-bd25-f492-1f6cf60e81be
spring.cloud.vault.app-role.secret-id=630e0794-23b6-0dc9-f5d0-8c676db4874f
spring.cloud.vault.app-role.role=minhajvault
spring.cloud.vault.app-role.app-role-path=approle

spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=kv

spring.cloud.vault.kv.default-context=secret/testpostgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/minhajvault
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

